#!/usr/bin/env python3

#Factorize Number

import sys
import math

def open_and_read_file(file_name):
    """ Read numbers from a file and return them as a list """
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    
    num_to_factor = [int(line) for line in lines]
    return num_to_factor

def factor_number(n):
    """ Factorize a number and print the factors """
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            print("{} = {} * {}".format(n, i, n // i))
            break

def factor_numbers(number_list):
    """ Factorize a list of numbers """
    for num in number_list:
        factor_number(num)

if len(sys.argv) == 2:
    input_file = sys.argv[1]
    num_to_factorize = open_and_read_file(input_file)
    factor_numbers(numbers_to_factorize)

